/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:896a464f-b843-4437-99a0-fd6dc78e7e2f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_s2LDbYxtr",
    "aws_user_pools_web_client_id": "7hl0ekusgrhs57ukreq01f7qvg",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://j6jgf47mzndbhpxisfztdpctqe.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gffp47lh6faglkyqlizorex3yq"
};


export default awsmobile;
